name: e2e-build
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - '*.kts'
      - 'tests/e2e/**'
      - 'libraries/core/**'
      - 'services/api/**'
      - 'services/filestore/**'
      - '.github/workflows/e2e-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew :tests:e2e:check
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
