name: filestore-build
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - '*.kts'
      - 'services/filestore/**'
      - 'libraries/core/**'
      - '.github/workflows/filestore-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew :services:filestore:check
